2025-02-05 23:33:48,394 - INFO - C:\projecte\face_to_unlock\webadmin\api\views.py changed, reloading.
2025-02-05 23:40:33,978 - WARNING - Not Found: /upload
2025-02-05 23:41:07,256 - WARNING - Not Found: /upload
2025-02-05 23:44:36,842 - WARNING - Not Found: /upload
2025-02-05 23:44:37,228 - WARNING - Not Found: /favicon.ico
2025-02-05 23:46:38,212 - INFO - C:\projecte\face_to_unlock\webadmin\api\urls.py changed, reloading.
2025-02-05 23:47:04,642 - ERROR - Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 243, in has_permission
    queryset = self._queryset(view)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 219, in _queryset
    assert hasattr(view, 'get_queryset') \
AssertionError: Cannot apply DjangoModelPermissionsOrAnonReadOnly on a view that does not set `.queryset` or have a `.get_queryset()` method.
2025-02-05 23:49:25,126 - ERROR - Internal Server Error: /api/upload
Traceback (most recent call last):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 192.168.0.101:8000/api/upload/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2025-02-05 23:54:39,689 - ERROR - Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 243, in has_permission
    queryset = self._queryset(view)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 219, in _queryset
    assert hasattr(view, 'get_queryset') \
AssertionError: Cannot apply DjangoModelPermissionsOrAnonReadOnly on a view that does not set `.queryset` or have a `.get_queryset()` method.
2025-02-05 23:55:51,519 - ERROR - Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 243, in has_permission
    queryset = self._queryset(view)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 219, in _queryset
    assert hasattr(view, 'get_queryset') \
AssertionError: Cannot apply DjangoModelPermissionsOrAnonReadOnly on a view that does not set `.queryset` or have a `.get_queryset()` method.
2025-02-05 23:58:18,203 - INFO - C:\projecte\face_to_unlock\webadmin\api\views.py changed, reloading.
2025-02-06 00:22:50,654 - ERROR - Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 497, in dispatch
    self.initial(request, *args, **kwargs)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 415, in initial
    self.check_permissions(request)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\views.py", line 332, in check_permissions
    if not permission.has_permission(request, self):
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 243, in has_permission
    queryset = self._queryset(view)
  File "C:\projecte\face_to_unlock\webadmin\env\lib\site-packages\rest_framework\permissions.py", line 219, in _queryset
    assert hasattr(view, 'get_queryset') \
AssertionError: Cannot apply DjangoModelPermissionsOrAnonReadOnly on a view that does not set `.queryset` or have a `.get_queryset()` method.
2025-02-06 00:37:53,726 - INFO - C:\projecte\face_to_unlock\webadmin\api\views.py changed, reloading.
